# This is a basic workflow to help you get started with Actions
 
name: Deploy Azure Function
 
# Controls when the action will run. 
on:
  # Triggers the workflow based on a release being published.
  release:
    types:
      - released
      - prereleased
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
env:
  FUNCTION_NAME: fun-use-core-dev    # This name needs to be globally unique
  SCRIPT_PATH: '.'      # set this to the path where your PowerShell code is stored.
  RESOURCE_GROUP: RGP-USE-CORE-DEV
  LOCATION: 'eastus'
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          enable-AzPSSession: true

      - name: Run Function
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript: 
            ${{ env.SCRIPT_PATH }}\tag-resources\run.ps1 -FunctionName ${{ env.FUNCTION_NAME }} -FunctionResourceGroup ${{ env.RESOURCE_GROUP }} -Location ${{ env.LOCATION }}
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest

      - name: Publish Azure App Service Profile
        uses: aliencube/publish-profile-actions@v1.2.0
        id: publishprofile
        with:
          # Resource group name.
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          # App instance name.
          appName: ${{ env.FUNCTION_NAME }}

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1.1.8
        with:
          # Name of the Azure Function App
          app-name: ${{ env.FUNCTION_NAME }}
          # Path to package or folder. *.zip or a folder to deploy
          package: ${{ env.SCRIPT_PATH }}
          # Publish profile (*.publishsettings) file contents with web deploy secrets
          publish-profile: ${{ steps.publishprofile.outputs.profile }}  

      - name: Clean Up Publish Profile
        uses: aliencube/publish-profile-actions@v1.2.0
        with:
          # Resource group name.
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          # App instance name.
          appName: ${{ env.FUNCTION_NAME }}
          # Value indicating whether to reset the publish profile or not.        
          reset: true